### ISSUE TITLE
Linux build documentation is incorrect (incomplete)

### ISSUE THREAD

**Issue by van-de-bugger** [sakhnik/nvim-ui#32]
Linux build documentation is incorrect. The documented commands being run in the freshly cloned repository fails:

    $ git clone https://github.com/sakhnik/nvim-ui.git
    <...output skipped...>
    $ cd nvim-ui
    $ meson setup BUILD --buildtype=debugoptimized
    <...skipped...>
    src/meson.build:1:0: ERROR: Non-existent build file 'src/gtkpp/meson.build'
    
    A full log can be found at .../nvim-ui/BUILD/meson-logs/meson-log.txt

Looks like `scripts/prepare-gtkpp.sh` must be run before `meson setup`.

**Comment by sakhnik** [comment]
Yes, the docs are doomed to lag behind. My plan is to implement signal handling in the generated c++ wrappers, port other widgets, and only then the docs are to catch up. Meanwhile, I'm using `scripts/build.sh` and `scripts/setup-lsp.sh`.
