### ISSUE TITLE
nvim-ui 0.1.0rc1 fails to build on linux

### ISSUE THREAD

**Issue by dpriedel** [sakhnik/nvim-ui#51]
`./scripts/build.sh 
created virtual environment CPython3.10.7.final.0-64 in 4273ms
  creator CPython3Posix(dest=/tmp/nvim-ui-0.1.0rc1/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/dpriedel/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==60.9.3, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivato
Cloning into 'gir2cpp'...
remote: Enumerating objects: 532, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 532 (delta 12), reused 24 (delta 7), pack-reused 494
Receiving objects: 100% (532/532), 69.12 KiB | 1.97 MiB/s, done.
Resolving deltas: 100% (358/358), done.
Note: switching to 'ac4a2770cdb03b2c41cb0683a5ace5fc56cdfc4d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Collecting Jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: MarkupSafe, Jinja2
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/tmp/nvim-ui-0.1.0rc1/venv/bin/python -m pip install --upgrade pip' command.
Unhandled {http://www.gtk.org/introspection/core/1.0}union
The Meson build system
Version: 0.63.2
Source dir: /tmp/nvim-ui-0.1.0rc1
Build dir: /tmp/nvim-ui-0.1.0rc1/BUILD
Build type: native build
Project name: nvim-ui
Project version: 0.1.0
C compiler for the host machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39.0
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (GCC) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.39.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency msgpack found: YES 4.0.0
Run-time dependency libuv found: YES 1.44.2
Run-time dependency spdlog found: YES 1.10.0
Run-time dependency fmt found: YES 9.1.0
Run-time dependency gtk4 found: YES 4.8.1

meson.build:22:0: ERROR: Subproject exists but has no CMakeLists.txt file
`

**Comment by sakhnik** [comment]
Does the project build on a fresh clone? Because I can't reproduce this.

**Comment by dpriedel** [comment]
I was trying to build from the source code bundle I had downloaded.
When I cloned the repository and then tried the build, it worked.
