### ISSUE TITLE
genappimage.sh fails on linux

### ISSUE THREAD

**Issue by dpriedel** [sakhnik/nvim-ui#52]
Using a newly cloned repositroy, running the genappimage.sh script fails.

`ARCH=x86_64 ./scripts/genappimage.sh 
The Meson build system
Version: 0.63.2
Source dir: /tmp/nvim-ui
Build dir: /tmp/nvim-ui/BUILD
Build type: native build
Project name: nvim-ui
Project version: 0.1.0
C compiler for the host machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39.0
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (GCC) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.39.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency msgpack found: YES 4.0.0
Run-time dependency libuv found: YES 1.44.2
Run-time dependency spdlog found: YES 1.10.0
Run-time dependency fmt found: YES 9.1.0
Run-time dependency gtk4 found: YES 4.8.1
Submodule 'subprojects/msgpack-c' (https://github.com/msgpack/msgpack-c) registered for path './'
Cloning into '/tmp/nvim-ui/subprojects/msgpack-c'...
Submodule path './': checked out '63511f29dbac8a1200a7653e561055e82e43d391'

Executing subproject msgpack-c method cmake 

msgpack-c| Found CMake: /usr/bin/cmake (3.24.2)

| Configuring the build directory with CMake version 3.24.2
| Running CMake with: -G Ninja -DCMAKE_INSTALL_PREFIX=/usr
|   - build directory:          /tmp/nvim-ui/BUILD/subprojects/msgpack-c/__CMake_build
|   - source directory:         /tmp/nvim-ui/subprojects/msgpack-c
|   - toolchain file:           /tmp/nvim-ui/BUILD/subprojects/msgpack-c/__CMake_build/CMakeMesonToolchainFile.cmake
|   - preload file:             /usr/lib/python3.10/site-packages/mesonbuild/cmake/data/preload.cmake
|   - trace args:               --trace-expand --trace-format=json-v1 --no-warn-unused-cli --trace-redirect=cmake_trace.txt
|   - disabled policy warnings: [CMP0025, CMP0047, CMP0056, CMP0060, CMP0065, CMP0066, CMP0067, CMP0082, CMP0089, CMP0102]

| Running with expanded trace output on.
| Not searching for unused variables given on the command line.
| Trace will be written to cmake_trace.txt
| -- The CXX compiler identification is GNU 12.2.0
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Check for working CXX compiler: /usr/bin/c++ - skipped
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Dynamically linking with Boost
| -- Found Boost: /usr/lib64/cmake/Boost-1.79.0/BoostConfig.cmake (found version "1.79.0")
| -- Found Doxygen: /usr/bin/doxygen (found version "1.9.3") found components: doxygen dot
| -- Configuring done
| -- Generating done
| -- Build files have been written to: /tmp/nvim-ui/BUILD/subprojects/msgpack-c/__CMake_build

msgpack-c| CMake configuration: SUCCEEDED
msgpack-c| CMake project msgpack has 2 build targets.

cmake-ast| Processing generated meson AST
cmake-ast| Build file: /tmp/nvim-ui/BUILD/subprojects/msgpack-c/meson.build

msgpack-c| Project name: msgpack
msgpack-c| Project version: undefined
msgpack-c| Build targets in project: 1
msgpack-c| Subproject msgpack-c finished.

Found pkg-config: /usr/bin/pkg-config (1.8.0)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)

src/meson.build:1:0: ERROR: Non-existent build file 'src/gtkpp/meson.build'

A full log can be found at /tmp/nvim-ui/BUILD/meson-logs/meson-log.txt

`

**Comment by sakhnik** [comment]
Thanks for reporting!
